# Generated by Django 4.1.2 on 2023-11-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_des', models.TextField()),
                ('movie_year', models.CharField(max_length=4)),
                ('movie_image', models.ImageField(upload_to='movies')),
            ],
        ),
    ]
